---
galaxy_info:
  role_name: manifold
  company: Princeton University Library
  description: Installs Manifold application
  author: pulibrary

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies:
  - role: "deploy_user"
  - role: "nginxplus"
  - role: "postgresql"
  - role: "ruby_s"
