---
# defaults file for mysql
#
# The address mysql should bind to.
mysql_bind_address: "127.0.0.1"


# The buffer pool size.
mysql_innodb_buffer_pool_size: 1G

# The io capacity.
mysql_innodb_io_capacity: 4000

# the host
mysql_host: 127.0.0.1
