---
mysql_server: true
mysql_host: "10.0.10.6"
mysql_bind_address: "0.0.0.0"
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_databases:
  - name: my_db
    encoding: utf8
    collation: utf8_bin
mysql_users:
  - name: my_user
    password: my_pass
    priv: "my_db.*:ALL"
    update_password: on_create
