---
nginx_setup: install
nginx_manage_repo: true
nginx_type: plus
nginx_http_template_enable: false
nginx_stream_template_enable: false
nginx_license:
  certificate: "license/nginx-repo.crt"
  key: "license/nginx-repo.key"
nginx_rest_api_enable: true
nginx_rest_api_write: true
nginx_modules:
  waf: true
  geoip: true
  njs: true
  perl: true
  image_filter: true
  rtmp: true
  xslt: true
nginx_status_enable: false
nginx_status_port: 8080
nginx_rest_api_src: api.conf.j2
nginx_rest_api_location: /etc/nginx/conf.d/api.conf
nginx_rest_api_port: 8080
nginx_rest_api_dashboard: true
nginx_delete_license: false
nginx_http_upload_enable: true
nginx_http_upload_src: conf/http/*.conf
nginx_http_upload_dest: /etc/nginx/conf.d/
nginx_stream_upload_enable: true
nginx_stream_upload_src: conf/stream/*.conf
nginx_stream_upload_dest: /etc/nginx/conf.d/stream/
nginx_cleanup_config: true
nginx_cleanup_config_path:
  - /etc/nginx/conf.d
nginx_ssl_upload_enable: true
nginx_ssl_crt_upload_src: ssl/*.pem
nginx_ssl_crt_upload_dest: /etc/nginx/conf.d/ssl/certs/
nginx_ssl_key_upload_src: ssl/*.key
nginx_ssl_key_upload_dest: /etc/nginx/conf.d/ssl/private/
nginx_template_upload_enable: true
nginx_template_upload_src: conf/http/templates/*.conf
nginx_template_upload_dest: /etc/nginx/conf.d/templates/
