---
galaxy_info:
  role_name: geoserver
  company: Princeton University Library
  description: Geoserver Role
  author: pulibrary

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

dependencies:
  # the playbook runs five roles in this order:
  # tomcat8, deploy_user, postgresql, samba, and geoserver
  # do we need to update this file?
  - role: deploy_user
  - role: tomcat8
