---
galaxy_info:
  role_name: ruby_s
  company: Princeton University Library
  description: Ruby Role
  author: pulibrary

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic

dependencies:
  - {role: common}
