---
# tasks file for system_ldap
#
- name: system_ldap | Install sssd
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  loop:
    - "{{ sssd_pkg_list }}"

- name: system_ldap | Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ sssd__unwanted_packages_state }}"
  loop:
    - "{{ sssd__unwanted_packages_list }}"

- name: system_ldap | configure krb5
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: 0644

- name: system_ldap | configure sudoers nsswitch.conf
  ansible.builtin.lineinfile:
    dest: /etc/nsswitch.conf
    state: present
    regexp: '^sudoers:'
    line: 'sudoers:        files'
    owner: root
    group: root
    mode: 0644

- name: system_ldap | Ensure home directories are created upon login with pam
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/common-account
    regexp: 'pam_mkhomedir\.so'
    line: "session required                        pam_mkhomedir.so        umask=0022      skel=/etc/skel/ silent"
    state: present

- name: system_ldap | change hostname to match AD 
  ansible.builtin.command: hostnamectl set-hostname {{ host_ad_name | default(omit)}}
  when:
    - running_on_server

- name: system_ldap | allow password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PasswordAuthentication no'
    line: 'PasswordAuthentication yes'

- name: system_ldap | allow users authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^AllowUsers pulsys'
    line: '# AllowUsers pulsys'

- name: system_ldap | Flush handlers to be able to use SSSD authentication
  meta: flush_handlers
