# File: roles/samba/tasks/main.yml
# For creating samba share, server-side
---
- name: Install Samba packages
  apt:
    name: ["samba-common", "samba", "samba-client", "cifs-utils"]
    state: present
  tags: samba

- include: samba_server.yml
