---
# handlers file for system_ldap
#
- name: restart sssd
  service:
    name: "{{ sssd_service_name }}"
    state: restarted

- name: restart logind
  service:
    name: systemd-logind
    state: restarted
