---
galaxy_info:
  role_name: nginxplus
  author: pulibrary
  description: nginxplus at PUL (see README)
  company: Princeton University Libraries

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal

dependencies:
  - role: 'common'
