---
galaxy_info:
  role_name: figgy
  company: Princeton University Library
  description: figgy
  author: pulibrary

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - jammy
dependencies:
  - role: "redis"
  - role: "kakadu"
  - role: "mediainfo"
  - role: "vips"
  - role: "imagemagick"
  - role: "subversion"
  - role: "freetds"
  - role: "rails_app"
  - role: "ffmpeg"
  - role: "extra_path"
  - role: "postgres"
