---
# Needed in order to add the rabbitmq repository
- name: rabbitmq | remove old erlang apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq-erlang/debian {{ ansible_distribution_release }} erlang-21.x'
    state: absent
    update_cache: false

- name: rabbitmq | remove old rabbitmq official apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main'
    state: absent
    update_cache: false

- name: rabbitmq | ensure software-properties-common is installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - gnupg
    - software-properties-common

- name: rabbitmq | import packagecloud
  block:
    - name: rabbitmq | import packagecloud key
      ansible.builtin.get_url:
        url: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
        dest: /usr/share/keyrings/io.packagecloud.rabbitmq.gpg
        mode: '0644'
        force: true

    - name: rabbitmq | add rabbitmq packagecloud repository
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: rabbitmq-packagecloud
      loop:
        - 'deb [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ jammy main'
        - 'deb-src [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ jammy main'

- name: rabbitmq | import cloudsmith
  block:
    - name: rabbitmq | import cloudsmith key
      ansible.builtin.get_url:
        url: "https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key"
        dest: /usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg
        mode: '0644'
        force: true

    - name: rabbitmq | add rabbitmq cloudsmith
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
        filename: rabbitmq-cloudsmith
      loop:
        - 'deb [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main'
        - 'deb-src [signed-by=/usr/share/keyrings/io.cloudsmith.rabbitmq.E495BB49CC4BBE5B.gpg] https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu jammy main'

- name: rabbitmq | install package
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present

- name: rabbitmq | enable rabbitmq plugins
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

- name: rabbitmq | add user
  community.rabbitmq.rabbitmq_user:
    user: '{{ rabbitmq_user }}'
    password: '{{ rabbitmq_password }}'
    tags: 'administrator, {{ rabbitmq_user }}'
    vhost: '/'
    configure_priv: '.*'
    write_priv: '.*'
    read_priv: '.*'
    state: present

- name: rabbitmq | remove default guest user
  community.rabbitmq.rabbitmq_user:
    user: guest
    state: absent
