---
# Needed in order to add the rabbitmq repository
- name: rabbitmq | remove old erlang apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq-erlang/debian {{ ansible_distribution_release }} erlang-21.x'
    state: absent
    update_cache: false

- name: rabbitmq | remove old rabbitmq official apt repository
  ansible.builtin.apt_repository:
    repo: 'deb https://dl.bintray.com/rabbitmq/debian {{ ansible_distribution_release }} main'
    state: absent
    update_cache: false

- name: rabbitmq | ensure software-properties-common is installed
  ansible.builtin.apt:
    name: ['software-properties-common', 'apt-transport-https']
    state: present

- name: rabbitmq | import rabbitmq key
  ansible.builtin.get_url:
    url: "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
    dest: /usr/share/keyrings/com.rabbitmq.team.gpg
    mode: '0644'
    force: true

- name: rabbitmq | import launchpad key
  ansible.builtin.get_url:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc"
    dest: /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg
    mode: '0644'
    force: true

- name: rabbitmq | import cloudsmith key
  ansible.builtin.get_url:
    url: "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey"
    dest: /usr/share/keyrings/io.packagecloud.rabbitmq.gpg
    mode: '0644'
    force: true

- name: rabbitmq | add rabbitmq repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/com.rabbitmq.team.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ ansible_distribution_release }} main'
    state: present

- name: rabbitmq | add rabbitmq launchpad src repository
  ansible.builtin.apt_repository:
    repo: 'deb-src [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu {{ ansible_distribution_release }} main'
    state: present

- name: rabbitmq | add rabbitmq cloudsmith
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_distribution_release }} main'
    state: present

- name: rabbitmq | add rabbitmq cloudsmith src
  ansible.builtin.apt_repository:
    repo: 'deb-src [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ {{ ansible_distribution_release }} main'
    state: present

- name: rabbitmq | install package
  ansible.builtin.apt:
    name: rabbitmq-server
    state: present

- name: rabbitmq | enable rabbitmq plugins
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  notify:
    - restart rabbitmq

- name: rabbitmq | add user
  community.rabbitmq.rabbitmq_user:
    user: '{{ rabbitmq_user }}'
    password: '{{ rabbitmq_password }}'
    tags: 'administrator, {{ rabbitmq_user }}'
    vhost: '/'
    configure_priv: '.*'
    write_priv: '.*'
    read_priv: '.*'
    state: present

- name: rabbitmq | remove default guest user
  community.rabbitmq.rabbitmq_user:
    user: guest
    state: absent
