---
galaxy_info:
  role_name: dpul
  author: pulibrary
  description: DPUL
  company: Princeton University Library

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 18.04

dependencies:
  - role: shared_data
  - role: ruby
  - role: deploy_user
  - role: passenger
  - role: redis
  - role: postgresql
  - role: nodejs
  - role: openjdk
  - role: imagemagick
  - role: rails_app
  # TODO: THis role runs with the line below commented out.  We need the line below to work
  # - {role: solr, when: postgresql_is_local == true}
  - role: sidekiq_worker
  - role: sneakers_worker
