---
postgresql_is_local: false
postgres_host: "lib-postgres-prod3.princeton.edu"
postgres_admin_user: "postgres"
postgres_admin_password: "{{ vault_postgres_admin_password }}"
postgres_version: 13
postgres_port: "5432"
pg_hba_contype: "host"
pg_hba_postgresql_user: "all"
pg_hba_postgresql_database: "all"
pg_hba_method: "md5"
pg_hba_source: "{{ ansible_host }}/32"
issuetracker_db_host: "{{ postgres_host }}"
issuetracker_db_name: "issuetracker_db"
issuetracker_db_user: "issuetracker_db_user"
issuetracker_db_password: "{{ vault_issuetracker_db_password }}"
