---
# tasks file for bugzilla
- name: bugzilla | install dependencies for bugzilla
  ansible.builtin.apt:
    name: "{{ bugzilla_packages }}"
    state: present
    update_cache: true

- name: bugzilla | install starman
  ansible.builtin.apt:
    name: starman
    state: present

- name: bugzilla | download bugzilla
  ansible.builtin.unarchive:
    src: "{{ mozilla_repo }}/webtools/bugzilla-{{ bugzilla_version }}/tar.gz"
    dest: "/var/www/"
    remote_src: true

      # - name: bugzilla | rename file directory
