---
# tasks file for manifold
- name: Manifold | download manifold installer
  ansible.builtin.get_url:
    url: "{{ manifold_download_url }}/{{ ubuntu_version }}/{{ manifold_version }}_amd64.deb"
    dest: /tmp/{{ manifold_version }}_amd64.deb
    mode: '0644'
  register: manifold_download
  retries: 3
  delay: 3600
  until: manifold_download is succeeded

- name: Manifold | install manifold package
  ansible.builtin.apt:
    deb: /tmp/{{ manifold_version }}_amd64.deb
