---
# tasks file for manifold
- name: Manifold | download manifold installer
  ansible.builtin.get_url:
    url: "{{ manifold_download_url }}/{{ ubuntu_version }}/{{ manifold_version }}_amd64.deb"
    dest: /tmp/{{ manifold_version }}_amd64.deb
    mode: '0644'

- name: Manifold | install manifold package
  ansible.builtin.apt:
    deb: /tmp/{{ manifold_version }}_amd64.deb