---
# tasks file for manifold
- name: Manifold | download manifold installer
  ansible.builtin.get_url:
    url: "{{ manifold_download_url }}/{{ ubuntu_version }}/{{ manifold_version }}_amd64.deb"
    dest: /tmp/{{ manifold_version }}_amd64.deb
    mode: '0644'
  register: manifold_download
  retries: 3
  delay: 3600
  until: manifold_download is succeeded

- name: Manifold | install manifold package
  ansible.builtin.apt:
    deb: /tmp/{{ manifold_version }}_amd64.deb

- name: Manifold | add template config
  ansible.builtin.template:
    src: manifold.rb.j2
    dest: /etc/manifold/manifold.rb
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0600'
  notify: restart manifold

- name: Manifold | reconfigure manifold
  ansible.builtin.command:
    cmd: /usr/bin/manifold-ctl reconfigure --accept-license
  changed_when: false

- name: Manifold | initialize user
  ansible.builtin.command:
    cmd: /usr/bin/manifold-api manifold:user:create:admin["{{ user_email }}","{{ user_password }}","{{ user_firstname }}","{{ user_lastname }}"]
  become: true
  become_user: "{{ deploy_user }}"
  changed_when: false
