---
galaxy_info:
  author: Princeton University Library
  description: Ouranos App. Deployment Service

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - 16.04
        - 18.04
dependencies:
  - role: 'rails_app'
    vars:
      rails_app_directory: 'ouranos'
      rails_app_name: 'ouranos'
      bundler_version: '2.2.19'
  - role: 'resque_worker'
    vars:
      resque_worker_name: 'ouranos-workers'
      rails_app_directory: 'ouranos'
      rails_app_name: 'ouranos'
      bundler_version: "2.2.19"
  - role: 'nodejs'
  - role: 'redis'
