---
- name: Install dependencies
  apt:
    name: ["cifs-utils", "python3-psycopg2"]
    state: present

- name: include tasks to mount disks
  include_tasks: mounts.yml

- name: include tasks to set redis config for workers
  include_tasks: redis_overcommit_memory.yml
  when: "'worker' in inventory_hostname"

