---
galaxy_info:
  role_name: nginxplusprotect
  company: Princeton University Library
  description: nginxplus WAF
  author: pulibrary

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - focal
dependencies:
  - role: "nginxplus"
