---
galaxy_info:
  role_name: bugzilla
  company: Princeton University Library
  author: pulibrary
  description: bugzilla role

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - bionic
dependencies:
  - role: "postgresql"
  - role: "apache2"
