---
- name: shared_data | Install dependencies
  ansible.builtin.apt:
    name: ["cifs-utils"]
    state: present

- name: shared_data | Copy smb credentials
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "/etc/{{ item }}"
    mode: 0644
  with_items:
    - shared_data.smb.credentials
  when: running_on_server

- name: shared_data | Create mount directories
  ansible.builtin.file:
    path: "/mnt/{{ item }}"
    state: "directory"
    mode: 0755
  with_items:
    - shared_data

- name: shared_data | Mount shared_data share
  ansible.posix.mount:
    name: "/mnt/shared_data"
    src: "//diglibdata1.princeton.edu/shared_data"
    fstype: cifs
    opts: "credentials=/etc/shared_data.smb.credentials,uid={{ deploy_user_uid }}"
    state: mounted
  when: running_on_server
