---
postgresql_is_local: false
postgres_host: "lib-postgres-staging3.princeton.edu"
postgres_version: 13
postgres_admin_user: "postgres"
pg_hba_contype: "host"
sensu_db_host: "{{ postgres_host }}"
sensu_db_name: sensu_data
sensu_db_user: sensu_pgsql
sensu_db_password: changeme # "{{ vault_sensu_staging_db_password }}"
application_db_name: "{{ sensu_db_name }}"
application_dbuser_name: "{{ sensu_db_user }}"
application_dbuser_password: "{{ sensu_db_password }}"
application_dbuser_role_attr_flags: "CREATEDB"
