---
galaxy_info:
  role_name: tigerdata
  company: Princeton University Library
  description: Creates a front facing web application for utilizing tigerdata
  author: pulibrary

  license: MIT

  min_ansible_version: 2.2

  platforms:
    - name: Ubuntu
      versions:
        - bionic
dependencies:
  - role: "rails_app"
  - role: "mailcatcher"
