---
deploy_user_local_keys:
  - { name: 'TowerDeployKey', key: "{{ lookup('file', '../keys/TowerDeployKey.pub') }}" }
  - { name: 'CodeDeployKey', key: "{{ lookup('file', '../keys/CodeDeployKey.pub') }}" }
  - { name: 'lib-proc4 service account', key: "{{ lookup('file', '../keys/lib-proc4.pub') }}" }
