---
# vars file for mysql
#
#
mysql_name: mariadb  # please be sure that this will install mariadb

mysql_packages:
  - mariadb-server
  - python3-mysqldb

mysql_client_packages:
  - mariadb-client
  - python3-dev
  - default-libmysqlclient-dev

mysql_service: mariadb

mysql_socket: /var/run/mysqld/mysqld.sock

mysql_configuration_options:
  - option: bind-address
    section: mysqld
    value: "{{ mysql_bind_address }}"
  - option: socket
    section: mysqld
    value: "{{ mysql_socket }}"
  - section: mysqld
    option: innodb_buffer_pool_size
    value: "{{ mysql_innodb_buffer_pool_size }}"
  - section: mysqld
    option: innodb_io_capacity
    value: "{{ mysql_innodb_io_capacity }}"

mysql_configuration_destination: /etc/mysql/mariadb.conf.d

mariadb_repo: "https://deb.mariadb.org"
mariadb_repo_version: 10.6
<<<<<<< HEAD
mariadb_repo_version: 10.3
=======
>>>>>>> fb58742f (install mariadb 10.6)
