---
- name: Converge
  hosts: all
  vars:
    - running_on_server: false
    - install_mailcatcher: true
  become: true
  pre_tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: true
  tasks:
    - name: "Include manifold"
      ansible.builtin.include_role:
        name: manifold
