---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: test for manifold binary existence
    ansible.builtin.stat:
      path: "{{ item }}"
    loop:
      - "/usr/bin/manifold-ctl"
    register: manifold_file
    failed_when:
      - not manifold_file.stat.exists
