---
- name: build Figgy
  hosts: figgy_staging
  remote_user: pulsys
  become: true
  pre_tasks:
    - name: remove mediainfo installation
      ansible.builtin.apt:
        name: mediainfo
        state: absent
    - name: remove mediainfo deb repo
      ansible.builtin.apt:
        name: repo-mediaarea
        state: absent
  vars_files:
    - ../site_vars.yml
    - ../group_vars/figgy/vault.yml
    - ../group_vars/figgy/staging.yml
  roles:
    - role: roles/memcached
    - role: roles/rabbitmq
    - role: roles/sidekiq_worker
    - role: roles/figgy
    - role: roles/figgy_pubsub_worker
    - role: roles/figgy_filewatcher_worker
  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      community.general.slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}"
        channel: #server-alerts
