---
- name: install geoserver
  hosts: geoserver
  remote_user: pulsys
  become: true
  vars_files:
    - ../site_vars.yml
    - ../group_vars/geoserver.yml
  roles:
    - role: roles/tomcat8
    - role: roles/deploy_user
    - role: roles/postgresql
    - role: roles/samba
    - role: roles/geoserver

  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      community.general.slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}"
        channel: #server-alerts
