---
- name: add a temp vm on google cloud to test our mysql role
  hosts: pas_gcp_dev
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/pas/pas_gcp_dev.yml
    - ../group_vars/pas/vault.yml
    - ../group_vars/gcp/dev.yml
    - ../group_vars/gcp/vault.yml
    - ../host_vars/gcp_mariadb_dev1.yml
  vars:
    - pas_upload_path: 'pas/pas-production'
  roles:
    - role: roles/pas
  post_tasks:
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: "{{ inventory_hostname }} completed"
        channel: #server-alerts
