---
- name: install postgresql on sensu
  hosts: sensu
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/sensu/production.yml
    # are we going to make the sensu db replicating?
    # - ../host_vars/lib-postgres-prod3.princeton.edu.yml
    # - ../host_vars/lib-postgres-prod2.princeton.edu.yml
    - ../group_vars/postgresql/vault.yml
  roles:
    - role: postgresql

  post_tasks:
    - name: Replace node identifier on "{{ leader_db_host }}"
      ansible.builtin.lineinfile:
        path: /etc/repmgr.conf
        regexp: "node_id=2"
        line: "node_id=1"
        owner: root
        group: root
        mode: '0644'
      delegate_to: "{{ leader_db_host }}"
    - name: tell everyone on slack you ran an ansible playbook
      slack:
        token: "{{ vault_pul_slack_token }}"
        msg: Ansible ran `{{ ansible_play_name }}` on {{ inventory_hostname }}
        channel: #server-alerts
