---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: check nfsserver package status
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    check_mode: true
    register: pkg_status
    loop:
      - nfs-kernel-server

  - name: test for ruby packages
    ansible.builtin.assert:
      that:
        - not pkg_status.changed
