---
- name: ruby_s | remove bundlers
  ansible.builtin.command: /usr/local/bin/gem uninstall bundler
  when: bundler_old_version is defined

- name: ruby_s | register gem path
  ansible.builtin.shell: /usr/local/bin/gem environment gemdir
  register: gem_dir
  when: bundler_old_version is defined

- name: ruby_s | output existing ruby version
  ansible.builtin.debug:
    msg: Installed ruby {{ gem_dir.stdout }}
  when: bundler_old_version is defined

- name: ruby_s | remove {{ bundler_old_version }} directory
  file:
    path: "{{ gem_dir.stdout }}/gems/bundler-{{ bundler_old_version }}"
    state: absent
  when: bundler_old_version is defined

- name: ruby_s | install global bundler, specific version
  ansible.builtin.command: /usr/local/bin/gem install bundler -v {{ bundler_version }}
  when: bundler_version is defined
