---
# these tasks download and install openssl 1.1.1
# instead of openssl 3, which
# ruby 2.7.5 cannot use
#
  - name: ruby_s | download openssl 1
    ansible.builtin.get_url:
      url: "{{ openssl_gzip_url }}/{{ openssl_version }}.tar.gz"
      dest: "{{ install_path }}/{{ openssl_version }}.tar.gz"

  - name: ruby_s | unzip openssl 1 file
    ansible.builtin.unarchive:
      src: "{{ install_path }}/{{ openssl_version }}.tar.gz"
      dest: "{{ install_path }}/"
      creates: "{{ install_path }}/{{ openssl_version }}"
      remote_src: true

  - name: ruby_s | configure openssl 1
    ansible.builtin.shell: cd {{ install_path }}/{{ openssl_version }} && ./config

  - name: ruby_s | make openssl 1
    ansible.builtin.shell: cd {{ install_path }}/{{ openssl_version }} && make && make test

