---
# the next 7 tasks download and install openssl 1.1.1 which
# ruby 2.7.5 cannot use openssl 3 because it does not know of its existence
#
- name: ruby_s | download openssl
  ansible.builtin.get_url:
    url: "{{ openssl_gzip_url }}"
    dest: "{{ install_path }}/{{ openssl_version }}.tar.gz"

- name: ruby_s | unzip openssl file
  ansible.builtin.unarchive:
    src: "{{ install_path }}/{{ openssl_version }}.tar.gz"
    dest: "{{ install_path }}/"
    creates: "{{ install_path }}/{{ openssl_version }}"
    copy: false

- name: ruby_s | configure openssl
  ansible.builtin.shell: cd {{ install_path }}/{{ openssl_version }} && ./configure shared zlib

- name: ruby_s | make openssl
  ansible.builtin.shell: cd {{ install_path }}/{{ openssl_version }} && make

- name: ruby_s | install openssl
  ansible.builtin.shell: cd {{ install_path }}/{{ openssl_version }} && make install
  become: true

- name: ruby_s | remove openssl certs directory
  ansible.builtin.file:
    path: "{{ install_path }}/{{ openssl_version }}/certs"
    state: absent

- name: ruby_s | Create OS certs symbolic link
  ansible.builtin.file:
    src: /etc/ssl/certs
    dest: "{{ install_path }}/{{ openssl_version }}/certs"
    owner: root
    group: root
    state: link

