---
- name: ruby_s | remove bundlers
  ansible.builtin.command: /usr/local/bin/gem uninstall bundler
  when: bundler_old_version is defined

- name: ruby_s | install global bundler, specific version
  ansible.builtin.command: /usr/local/bin/gem install bundler -v {{ bundler_version }}
  when: bundler_version is defined
