---
- name: check geoserver_version
  ansible.builtin.stat:
    path: /var/lib/tomcat8/webapps/{{ geoserver_file }}
  register: current_geoserver_file

- name: install or upgrade geoserver if necessary
  ansible.builtin.include_tasks:
    file: upgrade_geoserver.yml
  when: not current_geoserver_file.stat.exists
